// GENERATED by scripts/make-brand.mjs. Do not edit by hand.
//
// One file name per platform, served from /brand/. Each one was downloaded from
// that platform's own site and committed here, so we never hotlink and never
// leak a reader to a third party. The brands are their owners' trademarks; we
// show them to name the rights holder a reader is being sent to.
//
// A leading "!" means the mark is drawn in a dark colour and needs a pale plate
// behind it, or it would vanish into the tile.
export const LOGOS = {
  "WEBTOON": "webtoon.png",
  "Naver Webtoon": "naver-webtoon.png",
  "Naver Series": "naver-series.png",
  "Kakao Webtoon": "!kakao-webtoon.png",
  "KakaoPage": "kakaopage.png",
  "Tapas": "tapas.png",
  "Tappytoon": "tappytoon.png",
  "Lezhin": "lezhin.png",
  "Piccoma": "piccoma.png",
  "Manta": "manta.png",
  "Comikey": "comikey.png",
  "INKR": "inkr.png",
  "MANGA Plus": "manga-plus.png",
  "Manga Plus": "manga-plus.png",
  "VIZ": "viz.svg",
  "Yen Press": "yen-press.png",
  "Seven Seas Entertainment": "seven-seas-entertainment.png",
  "Kodansha": "kodansha.png",
  "Azuki": "!azuki.png",
  "Coolmic": "coolmic.png",
  "WebComics": "webcomics.png",
  "Bomtoon": "bomtoon.png",
  "Lalatoon": "lalatoon.png",
  "Toomics": "toomics.png",
  "Webnovel": "webnovel.png",
  "Pocket Comics": "pocket-comics.png",
  "NETCOMICS": "netcomics.png",
  "Bilibili Comics": "bilibili-comics.png",
  "KuaiKan Manhua": "kuaikan-manhua.png",
  "Tencent Comics": "tencent-comics.png",
  "Dongman Manhua": "dongman-manhua.png",
  "ONO": "ono.png",
  "Crunchyroll": "crunchyroll.png",
  "Netflix": "!netflix.png",
  "Hulu": "hulu.png",
  "Amazon Prime Video": "amazon-prime-video.png",
  "Disney Plus": "!disney-plus.png",
  "HIDIVE": "hidive.png",
  "Max": "!max.png",
  "YouTube": "!youtube.png",
  "Bilibili TV": "bilibili-tv.png",
  "Bilibili": "bilibili.png",
  "Tubi TV": "!tubi-tv.png",
  "Adult Swim": "!adult-swim.png",
  "iQ": "iq.png",
  "WeTV": "wetv.png",
  "Hoopla": "hoopla.png",
  "Star+": "!star.png",
}
