/**
 * Write src/lib/platform-logos.js from whatever is in public/brand/.
 *
 * Every logo is a file we downloaded once from the platform's own site and
 * committed. Nothing is hotlinked, so a reader's browser never tells a
 * platform which page they are on, and a platform going down cannot break us.
 *
 * The map is name -> file, not name -> slug, because two of our platform
 * names ("MANGA Plus" and "Manga Plus") share one slug and one file.
 *
 * Run it by hand after adding a logo: node scripts/make-brand.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import sharp from 'sharp'
import { PLATFORMS } from '../src/lib/platforms.js'

/**
 * A logo drawn in black disappears on a dark tile, and a logo drawn in white
 * disappears on a light one. So we look at the pixels instead of guessing:
 * average the brightness of everything that is not transparent, and hand the
 * dark ones a pale plate to stand on. Measured once, at build time.
 */
const isDark = async (path) => {
  if (path.endsWith('.svg')) {
    // An SVG has no pixels to read. Black fills are the only real risk.
    const text = readFileSync(path, 'utf8').toLowerCase()
    return /fill="#0|fill="black|fill="#1|fill="#2/.test(text)
  }
  const { data, info } = await sharp(path)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  let sum = 0
  let seen = 0
  for (let i = 0; i < data.length; i += info.channels) {
    if (data[i + 3] < 40) continue
    sum += 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2]
    seen += 1
  }
  return seen > 0 && sum / seen < 90
}

const slugOf = (n) => n.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const files = new Set(readdirSync(join(process.cwd(), 'public', 'brand')))
const rows = []
const missing = []
const darkOnes = []

for (const name of Object.keys(PLATFORMS)) {
  const slug = slugOf(name)
  const file = ['svg', 'png'].map((ext) => `${slug}.${ext}`).find((f) => files.has(f))
  if (!file) { missing.push(name); continue }
  const dark = await isDark(join(process.cwd(), 'public', 'brand', file))
  if (dark) darkOnes.push(name)
  rows.push(`  ${JSON.stringify(name)}: ${JSON.stringify(dark ? `!${file}` : file)},`)
}

const body = `// GENERATED by scripts/make-brand.mjs. Do not edit by hand.
//
// One file name per platform, served from /brand/. Each one was downloaded from
// that platform's own site and committed here, so we never hotlink and never
// leak a reader to a third party. The brands are their owners' trademarks; we
// show them to name the rights holder a reader is being sent to.
//
// A leading "!" means the mark is drawn in a dark colour and needs a pale plate
// behind it, or it would vanish into the tile.
export const LOGOS = {
${rows.join('\n')}
}
`

writeFileSync(join(process.cwd(), 'src', 'lib', 'platform-logos.js'), body)
console.log(`wrote src/lib/platform-logos.js — ${rows.length} logos, ${body.length} bytes`)
if (darkOnes.length) console.log(`pale plate: ${darkOnes.join(', ')}`)
if (missing.length) console.log(`no logo yet: ${missing.join(', ')}`)
