/**
 * Pull the brand marks we are allowed to use out of simple-icons, and write
 * them into src/lib/platform-logos.js.
 *
 * Why a generated file and not a runtime import: simple-icons is 3,460 icons
 * and several megabytes. The Worker has a 3 MB code budget for the WHOLE site.
 * We need fourteen paths, so fourteen paths is what gets committed.
 *
 * The icon paths are CC0. The brands themselves are trademarks of their
 * owners; we show them only to name the rights holder we are sending a reader
 * to, which is what a trademark is for.
 *
 * Run it by hand after adding a platform: node scripts/make-logos.mjs
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as simpleIcons from 'simple-icons'
import { PLATFORMS } from '../src/lib/platforms.js'

// Our platform name -> the simple-icons slug that is genuinely the same brand.
// Only exact brand matches belong here. A near-miss logo is worse than none.
const MAP = {
  'WEBTOON': 'webtoon',
  'Naver Webtoon': 'naver',
  'Naver Series': 'naver',
  'Kakao Webtoon': 'kakao',
  'KakaoPage': 'kakao',
  'Tapas': 'tapas',
  'Bilibili Comics': 'bilibili',
  'Bilibili': 'bilibili',
  'Bilibili TV': 'bilibili',
  'Crunchyroll': 'crunchyroll',
  'Netflix': 'netflix',
  'YouTube': 'youtube',
  'Tubi TV': 'tubi',
  'Max': 'max',
}

const bySlug = new Map()
for (const icon of Object.values(simpleIcons)) {
  if (icon && icon.slug && icon.path) bySlug.set(icon.slug, icon)
}

const rows = []
for (const [name, slug] of Object.entries(MAP)) {
  if (!PLATFORMS[name]) throw new Error(`${name} is not in platforms.js`)
  const icon = bySlug.get(slug)
  if (!icon) throw new Error(`simple-icons has no "${slug}" any more. Fix the map.`)
  rows.push(`  ${JSON.stringify(name)}: ${JSON.stringify(icon.path)},`)
}

const body = `// GENERATED by scripts/make-logos.mjs. Do not edit by hand.
//
// One SVG path per platform whose real mark we can legally ship. The paths come
// from simple-icons and are CC0; the brands are their owners' trademarks, shown
// here to name the rights holder a reader is being sent to.
//
// Every path is drawn inside a 24x24 box. A platform that is not in here gets a
// letter tile instead, which is why this file is allowed to be short.
export const LOGOS = {
${rows.join('\n')}
}
`

writeFileSync(join(process.cwd(), 'src', 'lib', 'platform-logos.js'), body)
console.log(`wrote src/lib/platform-logos.js — ${rows.length} marks, ${body.length} bytes`)
